import struct

PROTOCOL_VERSION = 1

# Cryptographic constants
AEAD_KEY_SIZE = 32
AEAD_NONCE_SIZE = 12
AEAD_TAG_SIZE = 16
AEAD_INFO = b"secure-messenger-v1"

X25519_KEY_SIZE = 32
SHA256_HASH_SIZE = 32
SHA512_HASH_SIZE = 64

# HKDF labels
HKDF_SALT_ROOT = b"SecureMessengerRootV1"
HKDF_SALT_CHAIN = b"SecureMessengerChainV1"
HKDF_SALT_MESSAGE = b"SecureMessengerMessageV1"
HKDF_SALT_IDENTITY = b"SecureMessengerIdentityV1"

# Double Ratchet constants
MAX_SKIP = 1000
RATCHET_KEY_SIZE = 32
CHAIN_KEY_SIZE = 32
MESSAGE_KEY_SIZE = 32

# SRP constants (3072-bit group, SHA-256)
SRP_PRIME_HEX = (
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
)
SRP_GENERATOR = 5
SRP_HASH_ALG = "sha256"

# Protocol message types
MSG_TYPE_TEXT = 1
MSG_TYPE_FILE = 2
MSG_TYPE_KEY_EXCHANGE = 3
MSG_TYPE_RATCHET_UPDATE = 4
MSG_TYPE_TYPING = 5
MSG_TYPE_READ_RECEIPT = 6
MSG_TYPE_DELETE = 7

# Prekey bundle fields
PREKEY_BUNDLE_VERSION = struct.pack("!H", 1)
ONE_TIME_PREKEY_COUNT = 100

# API routes
API_PREFIX = "/api/v1"
WS_PREFIX = "/ws/v1"
